title: Justin Meggitt
description:   
theme: minima
author:        

plugins:
  - jekyll-remote-theme

header_pages:
  - about.md
  - research.md
  - publications.md
  - lectures.md
  - teaching.md
  - media.md
  - contact.md
